name: üõ†Ô∏è Build + Unit tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/donations.json'
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-2022    # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: StatisticsAnalysisTool.sln
      Test_Project_Path: src\StatisticsAnalysisTool.UnitTests\StatisticsAnalysisTool.UnitTests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check for build errors
      run: dotnet build src\StatisticsAnalysisTool

    - name: Install dependencies
      run: dotnet restore src\StatisticsAnalysisTool

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # SDK Version to use; x will use the latest version of the 6.0 channel. Force 101 for global.json compatibility.
    - run: dotnet build src\StatisticsAnalysisTool

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
        # vs-version: '[17.1]'
        msbuild-architecture: x64

    - name: Execute unit tests
      if: ${{ matrix.configuration == 'Debug' }}
      run: dotnet test $env:Test_Project_Path
