name: ðŸ”¥ Create Release file by newest tag

on:
  push:
    tags:
      - 'v*'

jobs:

  build-application:
    name: Build and release application
    runs-on: windows-latest
    env:
      Project_File_Path: src\StatisticsAnalysisTool\StatisticsAnalysisTool.csproj

    steps:
    - name: ðŸ›’ Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: ðŸš§ Publish StatisticsAnalysisTool application in directory
      run: |
          dotnet publish $env:Project_File_Path -c Release -p:Platform=x64 -p:PublishDir=bin\Release -p:PublishProtocol=FileSystem -p:TargetFramework=net7.0-windows -p:RuntimeIdentifier=win-x64 -p:SelfContained=false -p:PublishSingleFile=true -p:PublishReadyToRun=false
    
    - name: ðŸ›  Create release zip file
      uses: vimtor/action-zip@v1
      with:
        files: src\StatisticsAnalysisTool\bin\Release
        dest: StatisticsAnalysis-AlbionOnline-${{ github.ref_name }}-x64.zip

    - name: ðŸš€ Upload release zip file to newest tag
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          StatisticsAnalysis-AlbionOnline-${{ github.ref_name }}-x64.zip