name: .NET Desktop

on:
  push:
    branches: [ master, dotnet-desktop.yml-update ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-2022    # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: StatisticsAnalysisTool.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - run: dotnet build src\StatisticsAnalysisTool

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
    #    vs-version: '[17.0,17.0]'
        msbuild-architecture: x64

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test src\StatisticsAnalysisTool.UnitTests

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      #run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      run: msbuild src\$env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
