name: ğŸ› ï¸ Build + Unit tests

on:
  pull_request:
    types: [review_requested, opened, reopened, synchronize]
    branches:
      - dev
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/donations.json'

jobs:

  build:
    if: "!contains(github.event.head_commit.message, '--wip')"
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-2022
    env:
      Solution_Name: StatisticsAnalysisTool.sln
      Test_Project_Path: src\StatisticsAnalysisTool.UnitTests\StatisticsAnalysisTool.UnitTests.csproj

    steps:
    - name: ğŸ›’ Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: ğŸ— dotnet restore
      run: dotnet restore src\StatisticsAnalysisTool
      
    - name: ğŸ›  dotnet build
      run: dotnet build src\StatisticsAnalysisTool --no-restore

    - name: ğŸ§ª Execute unit tests (Only debug)
      if: ${{ matrix.configuration == 'Debug' }}
      run: dotnet test $env:Test_Project_Path