name: ğŸ› ï¸ Build + Unit tests

on:
  pull_request:
    types: [review_requested, opened, reopened, synchronize]
    branches:
      - dev
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/donations.json'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-2022    # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: StatisticsAnalysisTool.sln
      Test_Project_Path: src\StatisticsAnalysisTool.UnitTests\StatisticsAnalysisTool.UnitTests.csproj

    steps:
    - name: ğŸ›’ Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: ğŸ— dotnet restore
      run: dotnet restore src
        
    - name: ğŸ›  dotnet build
      run: dotnet build --no-restore

    - name: ğŸ“¦ Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
        # vs-version: '[17.1]'
        msbuild-architecture: x64

    - name: ğŸ§ª Execute unit tests
      if: ${{ matrix.configuration == 'Debug' }}
      run: dotnet test $env:Test_Project_Path